server:
  port: 8762
spring:
  application:
    name: nativeConfigServer
#    配置文件的获取方式，native表示从本地获取
  profiles:
    active: native
#    本地配置文件存放的路劲
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
