server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    perfer-ip-address: true
#是否开启熔断机制
feign:
  hystrix:
    enabled: true
